version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: >
      --deterministic
      --accounts 10
      --host 0.0.0.0
      --networkId 1337
      --gasLimit 12000000
      --gasPrice 20000000000
      --mnemonic "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
    
  web3-school-backend:
    build: .
    depends_on:
      - ganache
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - TRUFFLE_NETWORK=development
    command: npm run deploy:local
    
  test:
    build: .
    depends_on:
      - ganache
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test
    
networks:
  default:
    driver: bridge
