name: Truffle Smart Contract Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Truffle globally
      run: npm install -g truffle
    
    - name: Start Ganache
      run: |
        npm install -g ganache-cli
        ganache-cli --deterministic --accounts 10 --host 0.0.0.0 --port 8545 &
        sleep 5
    
    - name: Compile contracts
      run: npm run compile
    
    - name: Check contract sizes
      run: npm run size-check
    
    - name: Run Truffle tests
      run: npm run test
    
    - name: Generate coverage report
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Solidity linter
      run: npm run lint

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm security audit
      run: npm audit --audit-level high
    
    - name: Install Python and Slither
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip
        pip3 install slither-analyzer
    
    - name: Compile contracts for Slither
      run: npm run compile
    
    - name: Run Slither security analysis
      run: slither contracts/ --print human-summary || true
